package com.latitude.genoapay.codingchallenge.controller.dto;

import java.time.LocalDateTime;
import java.util.List;

/**
 * Dtos could be generated by code generator, e.g. swagger-code-gen.
 */
public class MaxStockProfitRequest {
  private Long id;
  private LocalDateTime startDateTime;
  private LocalDateTime endDateTime;
  private List<Integer> stockPrices;

  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public LocalDateTime getStartDateTime() {
    return startDateTime;
  }

  public void setStartDateTime(LocalDateTime startDateTime) {
    this.startDateTime = startDateTime;
  }

  public LocalDateTime getEndDateTime() {
    return endDateTime;
  }

  public void setEndDateTime(LocalDateTime endDateTime) {
    this.endDateTime = endDateTime;
  }

  public List<Integer> getStockPrices() {
    return stockPrices;
  }

  public void setStockPrices(List<Integer> stockPrices) {
    this.stockPrices = stockPrices;
  }

  public MaxStockProfitRequest(Long id, LocalDateTime startDateTime, LocalDateTime endDateTime, List<Integer> stockPrices) {
    this.id = id;
    this.startDateTime = startDateTime;
    this.endDateTime = endDateTime;
    this.stockPrices = stockPrices;
  }

  public MaxStockProfitRequest() {
  }
}
